CREATE TABLE CVVALUEFIELD(
    CVVF_INC_PK SERIAL PRIMARY KEY NOT NULL UNIQUE,
    CVVF_OID        CHAR(32)    NOT NULL,
    CVVF_CODE   CHAR(16)  UNIQUE NOT NULL,
    CVVF_CLASSIFICATION_1           INTEGER     NOT NULL,
    CVVF_CLASSIFICATION_2           INTEGER     NOT NULL,
    CVVF_NAME       CHAR(32)    NOT NULL,
    CVVF_CLASSIFICATION     CHAR(32)    NOT NULL,
    CVVF_STATUS INTEGER     NOT NULL,
    CVVF_CREATED_DATETIME       TIMESTAMP   NOT NULL
);

CREATE TABLE CVVALUEFIELD_VALUE(
    V_INC_PK        SERIAL  NOT NULL,
    CVVF_INC_PK     INTEGER     NOT NULL,
    CVVF_VALUE      INTEGER     NOT NULL,
    CVVF_DEFINATION     CHAR(64)    NOT NULL,
    CVVF_NOTE           CHAR(128),
    CONSTRAINT CVVALUEFIELD_VALUE_PK    PRIMARY KEY(V_INC_PK,CVVF_INC_PK),
    CONSTRAINT CVVALUEFIELD_VALUE_FK FOREIGN KEY(CVVF_INC_PK) REFERENCES CVVALUEFIELD(CVVF_INC_PK) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);


CREATE TABLE VALUEFIELD(
    VF_INC_PK   SERIAL PRIMARY KEY NOT NULL UNIQUE,
    VF_OID      CHAR(32)    NOT NULL,
    VF_CODE     CHAR(16)  UNIQUE,
    VF_CLASSIFICATION_1         INTEGER     NOT NULL,
    VF_CLASSIFICATION_2         INTEGER     NOT NULL,
    VF_NAME     CHAR(32)    NOT NULL,
    VF_CLASSIFICATION   CHAR(32)    NOT NULL,
    VF_STATUS   INTEGER     NOT NULL,
    VF_CREATED_DATETIME     TIMESTAMP   NOT NULL
);

CREATE TABLE VALUEFIELD_VALUE(
    V_INC_PK SERIAL  NOT NULL,
    VF_INC_PK   INTEGER NOT NULL,
    VF_VALUE    INTEGER     NOT NULL,
    VF_DEFINATION   CHAR(64)    NOT NULL,
    VF_NOTE     CHAR(128),
    CONSTRAINT VALUEFIELD_VALUE_PK  PRIMARY KEY(V_INC_PK,VF_INC_PK),
    CONSTRAINT VALUEFIELD_VALUE_FK FOREIGN KEY(VF_INC_PK) REFERENCES VALUEFIELD(VF_INC_PK) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE DATAELEMENT(
    DE_INC_PK   SERIAL PRIMARY KEY NOT NULL,
    DE_DI   CHAR(32)  UNIQUE    NOT NULL,
    DE_THEME_CLASSIFICATION     INTEGER     NOT NULL,
    DE_CLASSIFICATION_1     INTEGER     NOT NULL,
    DE_CLASSIFICATION_2     INTEGER     NOT NULL,
    DE_NAME     CHAR(64)    NOT NULL,
    DE_DEFINATION       CHAR(256)   NOT NULL,
    DE_DATA_TYPE    INTEGER     NOT NULL,
    DE_PRESENT_FORMAT   CHAR(8)     NOT NULL,
    DE_ACCEPTABLE_VALUES    JSON,
    DE_ACCEPTABLE_VALUE_IF_ITERABLE     INTEGER     NOT NULL,
    DE_VALUE_FIELD_CODE     CHAR(16)  UNIQUE,
    DE_STATUS       INTEGER     NOT NULL,
    DE_CREATED_DATETIME     TIMESTAMP   NOT NULL,
    DE_VALUE_FIELD_IF_CV    INTEGER     NOT NULL
);


CREATE TABLE DATASET_META_DATA(
    DSMD_INC_PK     SERIAL  PRIMARY KEY     NOT NULL,
    DSMD_ID         CHAR(9)  UNIQUE     NOT NULL,
    DSMD_FIELD_CLASSIFICATION_1     INTEGER     NOT NULL,
    DSMD_FIELD_CLASSIFICATION_2     INTEGER     NOT NULL,
    DSMD_NAME       CHAR(64)  UNIQUE    NOT NULL,
    DSMD_STATUS     INTEGER     NOT NULL,
    DSMD_CREATED_DATETIME       TIMESTAMP       NOT NULL
);
CREATE TABLE DATASUBSET_META_DATA(
    DSSMD_INC_PK    SERIAL  PRIMARY KEY     NOT NULL,
    DSMD_INC_PK     INTEGER     NOT NULL,
    DSSMD_ID_C      CHAR(16),
    DSSMD_ID_G      CHAR(16),
    DSSMD_ID_P      CHAR(16),
    DSSMD_FIELD_CLASSIFICATION_1    INTEGER     NOT NULL,
    DSSMD_FIELD_CLASSIFICATION_2    INTEGER     NOT NULL,
    DSSMD_FIELD_CLASSIFICATION_3    INTEGER     NOT NULL,
    DSSMD_NAME      CHAR(64)    UNIQUE  NOT NULL,
    DSSMD_CREATED_DATETIME      TIMESTAMP       NOT NULL,
    DSSMD_STATUS    INTEGER     NOT NULL,
    CONSTRAINT DATASUBSET_META_DATA_FK  FOREIGN KEY(DSMD_INC_PK)    REFERENCES  DATASET_META_DATA(DSMD_INC_PK) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);
CREATE TABLE DATASUBSET(
    DSSMD_INC_PK        INTEGER             NOT NULL,
    DE_INC_PK           INTEGER             NOT NULL,
    DE_RID_C        CHAR(16),
    DE_RID_G        CHAR(16),
    DE_RID_P        CHAR(16),
    DSS_DE_STATUS   INTEGER     NOT NULL,
    CONSTRAINT DATASUBSET_PK    PRIMARY KEY(DSSMD_INC_PK,DE_INC_PK),
    CONSTRAINT DATASUBSET_FK1   FOREIGN KEY(DSSMD_INC_PK)   REFERENCES  DATASUBSET_META_DATA(DSSMD_INC_PK) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT DATASUBSET_FK12  FOREIGN KEY(DE_INC_PK)  REFERENCES  DATAELEMENT(DE_INC_PK) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE DATAELEMENT_ID_CLASSIFICATION(
    DEIDC_INC_PK    SERIAL      PRIMARY KEY     NOT NULL,
    DEIDC_CLASSIFICATION_1      INTEGER,
    DEIDC_CLASSIFICATION_1_NAME     CHAR(32),
    DEIDC_CLASSIFICATION_2      INTEGER,
    DEIDC_CLASSIFICATION_2_NAME     CHAR(32)
);


CREATE TABLE DATAELEMENT_RID_CLASSIFICATION(
    DERIDC_INC_PK   SERIAL      PRIMARY KEY     NOT NULL,
    DERIDC_CLASSIFICATION_1     INTEGER     NOT NULL,
    DERIDC_CLASSIFICATION_1_NAME    CHAR(32)    NOT NULL,
    DERIDC_CLASSIFICATION_2     INTEGER     NOT NULL,
    DERIDC_CLASSIFICATION_2_NAME    CHAR(32)    NOT NULL,
    DERIDC_CLASSIFICATION_3     INTEGER,
    DERIDC_CLASSIFICATION_3_NAME    CHAR(32)
);


















